/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PdDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLPdDrawerElement extends Components.PdDrawer, HTMLStencilElement {
    }
    var HTMLPdDrawerElement: {
        prototype: HTMLPdDrawerElement;
        new (): HTMLPdDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "pd-drawer": HTMLPdDrawerElement;
    }
}
declare namespace LocalJSX {
    interface PdDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "pd-drawer": PdDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pd-drawer": LocalJSX.PdDrawer & JSXBase.HTMLAttributes<HTMLPdDrawerElement>;
        }
    }
}
